version: '3.6'

volumes:
  cargo-registry:

services:
  poet-engine:
    image: sawtooth-poet-engine:${ISOLATION_ID}
    build:
      context: .
    volumes:
      - .:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "
